- hosts: localhost
  connection: local
  gather_facts: no
  sudo: yes

  tasks:
    - name: ghc/cabal-installのインストール
      apt: 
        name={{ item }} 
        update_cache=yes
      with_items:
        - ghc
        - cabal-install
