---
- hosts: localhost
  connection: local
  gather_facts: no
  become: no

  tasks:
    - name: homebrew をアップデート
      homebrew: update_homebrew=yes

    - name: ghc/cabal-install のインストール
      homebrew: name={{ item }} state=latest
      with_items:
        - ghc
        - cabal-install
