---
- hosts: localhost
  connection: local
  gather_facts: no
  become: no
  environment:
    HOMEBREW_CASK_OPTS: "--appdir=/Applications"
  tasks:
    - name: homebrew をアップデート
      homebrew: update_homebrew=yes

    - name: tap の追加
      homebrew_tap: name=caskroom/cask state=present

    - name: java のインストール
      homebrew_cask: name=java state=present

    - name: maven/gradle のインストール
      homebrew: name={{ item }} state=latest
      with_items:
        - maven
        - gradle
        - graphviz
