- hosts: localhost
  connection: local
  sudo: yes
  remote_user: vagrant

  tasks:
    - name: repositoryの追加
      apt_repository: repo='ppa:ondrej/php5-5.6'

    - name: php関連パッケージのインストール
      apt: name={{ item }} update_cache=yes
      with_items:
        - php5
        - php5-curl
        - php5-dev
        - php5-intl
        - php5-mcrypt
        - php5-xdebug

    - name: composerインストール
      shell: curl -sS https://getcomposer.org/installer | php

    - name: composerの設置
      copy: src=./composer.phar dest=/usr/local/bin/composer mode=775
