- hosts: localhost
  connection: local
  gather_facts: yes
  sudo: no

  tasks:
    - name: homebrew をアップデート
      homebrew: update_homebrew=yes

    - name: go のインストール
      homebrew: name=go state=latest install_options=cross-compile-common

    - name: go 環境設定
      copy:
        src: "{{ ansible_env.PWD }}/go.conf"
        dest: "~/.etc/go.conf"
