- hosts: localhost
  connection: local
  gather_facts: yes
  sudo: no

  tasks:
    - name: homebrew をアップデート
      homebrew: update_homebrew=yes

    - name: go のインストール
      homebrew: name={{ item }} state=latest
      with_items:
          - go

    - name: go 環境設定
      file:
        src: "{{ ansible_env.PWD }}/go.conf"
        dest: ~/.etc/go.conf
        state: link
        force: yes
