---
- hosts: localhost
  connection: local
  gather_facts: no
  become: no

  tasks:
    - name: homebrew をアップデート
      homebrew: update_homebrew=yes

    - name: pyenv のインストール
      homebrew: name=pyenv state=latest

    - name: pyenv-virtualenv のインストール
      homebrew: name=pyenv-virtualenv state=latest

    - name: 初期化処理の追加確認
      command: grep pyenv ~/.bash_profile
      register: init_confirm
      failed_when: init_confirm.rc < 0 or 1 < init_confirm.rc

    - name: 初期化処理の追加
      shell: cat python/pyenv.profile >> ~/.bash_profile
      when: init_confirm.rc == 1
