---
- hosts: localhost
  connection: local
  gather_facts: yes
  become: no

  tasks:
    - name: homebrew をアップデート
      homebrew: update_homebrew=yes

    - name: pyenv のインストール
      homebrew: name=pyenv state=latest

    - name: pyenv-virtualenv のインストール
      homebrew: name=pyenv-virtualenv state=latest

    - name: pyenv 環境設定
      copy:
        src: "{{ ansible_env.PWD }}/python/pyenv.conf"
        dest: "~/.etc/pyenv.conf"
