---
- hosts: localhost
  connection: local
  gather_facts: yes
  become: yes

  tasks:
    - name: 利用パッケージのインストール
      apt: name={{ item }} update_cache=yes
      with_items:
        - python
        - python3
        - python-pip

    - name: virtualenv/virtualenvwrapper のインストール
      shell: pip install virtualenv virtualenvwrapper

    - name: virtualenv 設定
      sudo: no
      copy:
        src: "{{ ansible_env.PWD }}/python.conf"
        dest: "~/.etc/python.conf"
